// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;
import "../Structs.sol";
import "../State/IState.sol";
import "@openzeppelin/contracts/interfaces/IERC5267.sol";

interface ISignatureTransfer is IERC5267, IState {
    // keccak256("TransferWithCommit(address from,address to,address token,address executor,uint256 value,uint256 validAfter,uint256 validBefore,bytes32 commitment)")
    function TRANSFER_WITH_COMMIT_TYPEHASH() external view returns (bytes32);
    // keccak256("UniCommitTransfers(address from,address executor,TransferDetail[] details,uint256 validAfter,uint256 validBefore,bytes32 commitment)TransferDetail(address to,address token,uint256 value)")
    function UNI_COMMIT_TRANSFER_TYPEHASH() external view returns (bytes32);
    // keccak256("BatchTransferWithCommit(address from,address executor,CommittedTransferDetail[] details,uint256 validAfter,uint256 validBefore,bytes32 batchCommitment)CommittedTransferDetail(address to,address token,uint256 value,bytes32 commitment)")
    function BATCH_TRANSFER_WITH_COMMIT_TYPEHASH() external view returns (bytes32);
    // keccak256("CancelAuthorization(address authorizer,bytes32 commitment)")
    function CANCEL_AUTHORIZATION_TYPEHASH() external view returns (bytes32);

    /**
     * @notice Execute a transfer with a signed authorization
     * @notice Only the sender specified by the signer can execute it.
     * @param from  Payer's address
     * @param to Payee's address
     * @param token Token address
     * @param value Amount to be transferred
     * @param validAfter The time after which this is valid (unix time)
     * @param validBefore The time before which this is valid (unix time)
     * @param commitment Unique commitment
     * @param signature Signature generated by the signer
     */
    function transferWithAuthorization(
        address from,
        address to,
        address token,
        uint256 value,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 commitment,
        bytes calldata signature
    ) external;

    /**
     * @notice Execute a batch transfer with a signed authorization
     * @notice Only the executor specified by the signer can execute it.
     * @param from  Payer's address
     * @param details Array of transfer details. Each element includes token address, payee address and amount.
     * @param validAfter The time after which this is valid (unix time)
     * @param validBefore The time before which this is valid (unix time)
     * @param batchCommitment Batch-level commitment (EIP-712 field); consumed by `replayGuard(from, batchCommitment)`.
     * @param signature Signature generated by the signer
     */
    function transferWithAuthorization(
        address from,
        CommittedTransferDetail[] calldata details,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 batchCommitment,
        bytes calldata signature
    ) external;

    /**
     * @notice Execute a batch transfer with a signed authorization
     * @notice Only the sender specified by the signer can execute it.
     * @param from  Payer's address
     * @param details Array of transfer details. Each element includes token address, payee address and amount.
     * @param validAfter The time after which this is valid (unix time)
     * @param validBefore The time before which this is valid (unix time)
     * @param commitment Unique commitment
     * @param signature Signature generated by the signer
     */
    function transferWithAuthorization(
        address from,
        TransferDetail[] calldata details,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 commitment,
        bytes calldata signature
    ) external;

    /**
     * @notice Attempt to cancel an authorization
     * @param authorizer    Authorizer's address
     * @param commitment    Unique commitment
     * @param signature Signature generated by the signer
     */
    function cancelAuthorization(address authorizer, bytes32 commitment, bytes calldata signature) external;
}
