// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;
import "../Events.sol";
import "./ISignatureTransfer.sol";
import "./Hash.sol";
import "../State/State.sol";
import "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

contract SignatureTransfer is ISignatureTransfer, State, EIP712, ReentrancyGuard {
    using SafeERC20 for IERC20;

    constructor(string memory name, string memory version) EIP712(name, version) {}

    bytes32 public constant TRANSFER_WITH_COMMIT_TYPEHASH = Hash.TRANSFER_WITH_COMMIT_TYPEHASH;
    bytes32 public constant BATCH_TRANSFER_WITH_COMMIT_TYPEHASH = Hash.BATCH_TRANSFER_WITH_COMMIT_TYPEHASH;
    bytes32 public constant UNI_COMMIT_TRANSFER_TYPEHASH = Hash.UNI_COMMIT_TRANSFER_TYPEHASH;
    // keccak256("CancelAuthorization(address authorizer,bytes32 commitment)")
    bytes32 public constant CANCEL_AUTHORIZATION_TYPEHASH =
        0x36cf110689efdef752c1697fa06ba1de348f72954cebdc346d5b55050ff0c8ec;

    modifier validTimestamp(uint256 validAfter, uint256 validBefore) {
        require(
            validAfter <= validBefore,
            "TransferWithCommitment: The `validAfter` and `validBefore` must be `validAfter<=validBefore`"
        );
        require(block.timestamp > validAfter, "TransferWithCommitment: Signature is not yet valid");
        require(block.timestamp < validBefore, "TransferWithCommitment: Signature is expired");
        _;
    }

    /**
     * @notice A single transfer that includes a commitment
     * @notice Only the executor specified by the signer can execute it.
     * @param from  Payer's address
     * @param to Payee's address
     * @param token Token address
     * @param value Amount to be transferred
     * @param validAfter The time after which this is valid (unix time)
     * @param validBefore The time before which this is valid (unix time)
     * @param commitment Unique commitment
     * @param signature Signature generated by the signer
     */
    function transferWithAuthorization(
        address from,
        address to,
        address token,
        uint256 value,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 commitment,
        bytes calldata signature
    ) external nonReentrant validTimestamp(validAfter, validBefore) replayGuard(from, commitment) {
        bytes32 structHash = keccak256(
            abi.encode(
                TRANSFER_WITH_COMMIT_TYPEHASH, from, to, token, msg.sender, value, validAfter, validBefore, commitment
            )
        );
        bytes32 digest = _hashTypedDataV4(structHash);
        require(
            SignatureChecker.isValidSignatureNow(from, digest, signature), "TransferWithCommitment: Invalid signature"
        );

        _transfer(token, from, to, value, commitment);
    }

    /**
     * @notice Execute a batch transfer with a signed authorization
     * @notice Only the executor specified by the signer can execute it.
     * @param from  Payer's address
     * @param details Array of transfer details. Each element includes token address, payee address and amount.
     * @param validAfter The time after which this is valid (unix time)
     * @param validBefore The time before which this is valid (unix time)
     * @param signature Signature generated by the signer
     */
    function transferWithAuthorization(
        address from,
        CommittedTransferDetail[] calldata details,
        uint256 validAfter,
        uint256 validBefore,
        bytes calldata signature
    ) external nonReentrant validTimestamp(validAfter, validBefore) {
        require(details.length > 0, "TransferWithCommitment: The length of `details` must be at least 1");
        bytes32 committedTransferDetailsHash = Hash.hashBatchCommittedTransferDetails(details);
        bytes32 structHash = keccak256(
            abi.encode(
                BATCH_TRANSFER_WITH_COMMIT_TYPEHASH,
                from,
                msg.sender,
                committedTransferDetailsHash,
                validAfter,
                validBefore
            )
        );
        bytes32 digest = _hashTypedDataV4(structHash);
        require(
            SignatureChecker.isValidSignatureNow(from, digest, signature), "TransferWithCommitment: Invalid signature"
        );

        _batchTransfers(from, details);
    }

    /**
     * @notice Execute a unified committed transfer with a signed authorization
     * @notice Only the executor specified by the signer can execute it.
     * @param from  Payer's address
     * @param details Array of transfer details. Each element includes token address, payee address and amount.
     * @param validAfter The time after which this is valid (unix time)
     * @param validBefore The time before which this is valid (unix time)
     * @param commitment Unique commitment
     * @param signature Signature generated by the signer
     */
    function transferWithAuthorization(
        address from,
        TransferDetail[] calldata details,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 commitment,
        bytes calldata signature
    ) external nonReentrant validTimestamp(validAfter, validBefore) replayGuard(from, commitment) {
        require(details.length > 0, "TransferWithCommitment: The length of `details` must be at least 1");
        bytes32 transferDetailsHash = Hash.hashBatchTransferDetails(details);
        bytes32 structHash = keccak256(
            abi.encode(
                UNI_COMMIT_TRANSFER_TYPEHASH, from, msg.sender, transferDetailsHash, validAfter, validBefore, commitment
            )
        );
        bytes32 digest = _hashTypedDataV4(structHash);
        require(
            SignatureChecker.isValidSignatureNow(from, digest, signature), "TransferWithCommitment: Invalid signature"
        );

        _unifiedTransfers(from, details, commitment);
    }

    function _batchTransfers(address from, CommittedTransferDetail[] calldata details) private {
        for (uint256 i = 0; i < details.length; i++) {
            CommittedTransferDetail calldata detail = details[i];
            _transferWithGuard(detail.token, from, detail.to, detail.value, detail.commitment);
        }
    }

    function _unifiedTransfers(address from, TransferDetail[] calldata details, bytes32 commitment) private {
        for (uint256 i = 0; i < details.length; i++) {
            TransferDetail calldata detail = details[i];
            _transfer(detail.token, from, detail.to, detail.value, commitment);
        }
    }

    /**
     * @notice Attempt to cancel an authorization
     * @param authorizer    Authorizer's address
     * @param commitment    Unique commitment
     * @param signature Signature generated by the signer
     */
    function cancelAuthorization(address authorizer, bytes32 commitment, bytes calldata signature)
        external
        nonReentrant
        replayGuard(authorizer, commitment)
    {
        bytes32 structHash = keccak256(abi.encode(CANCEL_AUTHORIZATION_TYPEHASH, authorizer, commitment));
        bytes32 digest = _hashTypedDataV4(structHash);
        require(
            SignatureChecker.isValidSignatureNow(authorizer, digest, signature),
            "TransferWithCommitment: Invalid signature"
        );
    }

    function _transferWithGuard(address token, address from, address to, uint256 value, bytes32 commitment)
        private
        replayGuard(from, commitment)
    {
        _transfer(token, from, to, value, commitment);
    }

    function _transfer(address token, address from, address to, uint256 value, bytes32 commitment) private {
        IERC20 tokenContract = IERC20(token);
        if (tokenContract.allowance(from, address(this)) < value) {
            revert AllowanceNotEnough(token, from, value);
        }
        tokenContract.safeTransferFrom(from, to, value);
        emit TransferWithCommitmentSent(from, to, token, value, commitment);
    }
}
